#!/usr/bin/perl -w

###
# Tinhorn: script/console
# Runs the Tinhorn console in standalone mode
# Copyright (c) 2010 by Dann Stayskal.  All rights reserved.
###

use strict;
use lib qw( lib/perl/ );
use Tinhorn qw( start_console );
exit !start_console();
